server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka

spring:
  application:
    name: community-service
  datasource:
    url: jdbc:mysql://community_mysql:3306/community?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 250
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: funfit
  data:
    mongodb:
      uri: mongodb://root:root@mongo:27017/funfit?authSource=admin
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 4
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
  instances:
    auth:
      baseConfig: default

logging:
  level:
    org:
      hibernate.SQL: debug
jwt:
  secret: flwkegnwoirgnoaeringaleriknglakernglekrng # ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: funfit.community
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alph

openapi:
  service:
    url: http://gateway-service:8080
